# Generated by Django 3.0.3 on 2020-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='total_max_amount',
            field=models.FloatField(),
        ),
    ]
