# Generated by Django 3.0.3 on 2020-02-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20200219_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='benefit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
